package com.duanxin.hwjy.infrastructure.common.constants;

/**
 * @author duanxin
 * @version 1.0
 * @className CounterConstants
 * @date 2021/02/20 09:06
 */
public enum CounterConstants {

    GARBAGE_NEWS_COUNTER,
    INTEGRAL_COLLECT_BY_WATCH_NEWS_COUNTER,
    INTEGRAL_COLLECT_BY_GARBAGE_IDENTIFICATION_WITH_TEXT_COUNTER,
    INTEGRAL_COLLECT_BY_GARBAGE_IDENTIFICATION_WITH_PICTURES_COUNTER,
    INTEGRAL_COLLECT_BY_GARBAGE_IDENTIFICATION_WITH_LANGUAGE_COUNTER,

}
